server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: request-payment
          uri: http://localhost:8052
          predicates:
            - Path=/payments/**, 
        - id: reservation
          uri: http://localhost:8072
          predicates:
            - Path=/reservations/**, 
        - id: notification
          uri: http://localhost:8073
          predicates:
            - Path=/notifications/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: spec
          uri: http://localhost:8082
          predicates:
            - Path=/specComparations/**, /specs/**, 
        - id: order
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**, 
        - id: marketing
          uri: http://localhost:8084
          predicates:
            - Path=/retargettings/**, 
        - id: insurance
          uri: http://localhost:8085
          predicates:
            - Path=/insuranceSubscriptions/**, 
        - id: salesdashboard
          uri: http://localhost:8086
          predicates:
            - Path=/salesData/**, /salesDashBoards/**
        - id: user
          uri: http://localhost:8087
          predicates:
            - Path=/users/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "X-Total-Count"
              - "Link"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: spec
          uri: http://spec:8080
          predicates:
            - Path=/specComparations/**, /specs/**, 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/retargettings/**, 
        - id: insurance
          uri: http://insurance:8080
          predicates:
            - Path=/insuranceSubscriptions/**, 
        - id: salesdashboard
          uri: http://salesdashboard:8080
          predicates:
            - Path=/salesData/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
