---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentpbcfe
  labels:
    app: paymentpbcfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentpbcfe
  template:
    metadata:
      labels:
        app: paymentpbcfe
    spec:
      containers:
        - name: paymentpbcfe
          image: "user11registry.azurecr.io/paymentpbcfe:0501"
          ports:
            - containerPort: 8080